#!/bin/sh
if [ -z "$1" ];then 
	echo "Error : empty string"
	exit 1
fi
if [ -z "$2" ];then 
	echo "Error: empty string"
	exit 1
fi

if [ "$1" -le  0 ];then 
	echo "Input must be greater than 0"
	exit 1
fi	
if [ "$2" -le 0 ];then
	echo "Input must be greater than 0"
	exit 1
fi
for i in $(seq 1 $1);do
	for j in $(seq 1 $2);do
	result=`expr $i \* $j`
	printf "%d*%d=%d  " $i $j $result
done
printf "\n"
done

exit 0
